version: "3.9"

services:
  #Laravel App
  app:
    build:
      context: .
      dockerfile: ./docker/local.dockerfile
    image: laravel_nginx_server_app
    container_name: clothes-shopping_app
    working_dir: /var/www/html/app
    tty: true
    volumes:
      - .:/var/www/html/app
      - ./docker/config/php/php.ini-development:/usr/local/etc/php/php.ini
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:1.19.6-alpine
    container_name: clothes-shopping_nginx_server
    tty: true
    ports:
      - "9999:80"
      - "7749:443"
    volumes:
      - .:/var/www/html/app
      - ./docker/config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0
    container_name: clothes-shopping_mysql_db
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/config/mysql/:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #   MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3396:3306"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local
